### ISSUE TITLE
DEBUG messages for imprint polluting log

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-acdhch-default-settings#118]
Is there a way to disable log messages for missing imprint data when `ACDH_IMPRINT_URL`/`REDMINE_ID` don't exist yet and logging hasn't yet been configured for local development, either? 

They are kind of annoying during project setup:
```
MY_DATETIME urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): imprint.acdh.oeaw.ac.at:443
MY_DATETIME urllib3.connectionpool DEBUG    https://imprint.acdh.oeaw.ac.at:443 "GET / HTTP/11" 200 2
```

**Comment by koeaw** [comment]
I guess the idea is to remind people to set `REDMINE_ID` for live sites, but for projects which aren't deployed yet, for which there isn't even a Redmine ticket yet, that's not relevant.

Isn't the `REDMINE_ID` a required setting for deployments to work in the first place? Though I might be confusing this with something else (frontend deployments, possibly).

Idk if this check could e.g. be disabled if `DEBUG = True` or if this would defeat the purpose of the check in the first place.

**Comment by b1rger** [comment]
> Is there a way to disable log messages for missing imprint data when `ACDH_IMPRINT_URL`/`REDMINE_ID` don't exist yet and logging hasn't yet been configured for local development, either?

There are no log messages for missing imprint data. The log messages you are quoting come from `urllib3`, whenever a request is made.
