### ISSUE TITLE
Differences between Django default settings and apis-acdhch-default-settings

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-acdhch-default-settings#120]
I followed the Core docs for initial project setup, so already had a settings.py file in place before adding  `apis-acdhch-default-settings` as dependency.

I ended up paring down that file, removing variables present in our shared [settings.py](https://github.com/acdh-oeaw/apis-acdhch-default-settings/blob/fb3947c85ba711723b72453df7ebe7db8f9a189b/apis_acdhch_default_settings/settings.py) file and checking Frischmuth for additional variables to add. While doing so, I noticed a couple of differences between our defaults and Django's current defaults. Was wondering if our settings are "behind" because they are based on older versions of Django (some of the comments reference old versions of the docs) and should be updated, or if they were intentionally changed.

Django currently (5.1) uses the following for `BASE_DIR`:
```python
BASE_DIR = Path(__file__).resolve().parent.parent
```

We use:
https://github.com/acdh-oeaw/apis-acdhch-default-settings/blob/fb3947c85ba711723b72453df7ebe7db8f9a189b/apis_acdhch_default_settings/settings.py#L29-L31

Django includes a `DEFAULT_AUTO_FIELD` setting:

```python
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
```
which we are missing.

**Comment by b1rger** [comment]
fixed in d0c77ba075a3ae25927c077f19cdbdecb6038998 and 1208d9c66c6145c0d463217f13b59592059ec6f9
